# build environment
FROM node:10.15.1 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
#declare arguments
ARG NODE_ENV
ARG REACT_APP_SERVICE_URL
ARG AUTH_COOKIE_DOMAIN
ARG REACT_APP_ENV
ARG REACT_APP_PROFILE_URL

# expose environment to the new container
ENV NODE_ENV $NODE_ENV
ENV AUTH_COOKIE_DOMAIN $AUTH_COOKIE_DOMAIN
ENV REACT_APP_SERVICE_URL $REACT_APP_SERVICE_URL
ENV REACT_APP_ENV $REACT_APP_ENV
ENV REACT_APP_PROFILE_URL $REACT_APP_PROFILE_URL

COPY package.json /usr/src/app/package.json
RUN npm install --silent
COPY . /usr/src/app
RUN npm run build:staging

# production environment
FROM nginx:1.15.8-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]